---
- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: restart syslog
  service: name=rsyslog state=restarted

- name: update motd
  command: run-parts /etc/update-motd.d/

- name: restart sshd
  service:
    name: ssh
    state: restarted
